"""drop character is main

Revision ID: 03d0cd6a4f18
Revises:80d1287be149
Create Date: 2026-09-09 12:55:35.584917
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '03d0cd6a4f18'
down_revision: str | None = '80d1287be149'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('is_main')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_main', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
