"""initial schema

Revision ID: 0cf95adcb590
Revises:
Create Date: 2026-09-08 13:21:55.149019
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0cf95adcb590"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("discord_user_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="uq_character_guild_name"),
    )
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.create_index(
            "ix_character_guild_user", ["guild_id", "discord_user_id"], unique=False
        )

    op.create_table(
        "guild_config",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("notify_channel_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("guild_id"),
    )
    op.create_table(
        "party_schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("boss_name", sa.String(length=32), nullable=False),
        sa.Column("difficulty", sa.String(length=16), nullable=False),
        sa.Column("repeat_type", sa.String(length=16), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=True),
        sa.Column("month_day", sa.Integer(), nullable=True),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("party_schedule", schema=None) as batch_op:
        batch_op.create_index(
            "ix_party_schedule_guild_active", ["guild_id", "is_active"], unique=False
        )

    op.create_table(
        "clear_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("boss_name", sa.String(length=32), nullable=False),
        sa.Column("difficulty", sa.String(length=16), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_key", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schedule_id"], ["party_schedule.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id", "boss_name", "difficulty", "period_key", name="uq_clear_record_period"
        ),
    )
    with op.batch_alter_table("clear_record", schema=None) as batch_op:
        batch_op.create_index(
            "ix_clear_record_guild_period", ["guild_id", "period_key"], unique=False
        )

    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("occurrence_key", sa.String(length=32), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["schedule_id"], ["party_schedule.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id", "kind", "occurrence_key", name="uq_notification_once"),
    )
    op.create_table(
        "party_member",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schedule_id"], ["party_schedule.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id", "character_id", name="uq_party_member_schedule_char"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("party_member")
    op.drop_table("notification_log")
    with op.batch_alter_table("clear_record", schema=None) as batch_op:
        batch_op.drop_index("ix_clear_record_guild_period")

    op.drop_table("clear_record")
    with op.batch_alter_table("party_schedule", schema=None) as batch_op:
        batch_op.drop_index("ix_party_schedule_guild_active")

    op.drop_table("party_schedule")
    op.drop_table("guild_config")
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.drop_index("ix_character_guild_user")

    op.drop_table("character")
    # ### end Alembic commands ###
