"""drop boss image table

Revision ID: 5c7d46616aae
Revises:f8af749de87f
Create Date: 2026-09-08 13:58:04.465461
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5c7d46616aae"
down_revision: str | None = "f8af749de87f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("boss_image")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boss_image",
        sa.Column("guild_id", sa.BIGINT(), nullable=False),
        sa.Column("boss_name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("image_url", sa.VARCHAR(length=500), nullable=False),
        sa.PrimaryKeyConstraint("guild_id", "boss_name"),
    )
    # ### end Alembic commands ###
