"""add party schedule code

Revision ID: 80d1287be149
Revises:5c7d46616aae
Create Date: 2026-09-08 14:49:03.652461
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "80d1287be149"
down_revision: str | None = "5c7d46616aae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("party_schedule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code", sa.String(length=8), nullable=True))
        batch_op.create_unique_constraint("uq_party_schedule_guild_code", ["guild_id", "code"])

    _backfill_codes()


def _backfill_codes() -> None:
    """이미 있던 일정에도 코드를 하나씩 붙인다.

    code가 비어 있으면 자동완성에도 안 잡히고 수정·삭제도 못 하므로,
    컬럼만 추가하고 끝내면 기존 파티가 손댈 수 없는 상태가 된다.
    """
    from bot.domain.code import generate_code

    connection = op.get_bind()
    rows = connection.execute(
        sa.text(
            "SELECT id, guild_id, boss_name FROM party_schedule"
            " WHERE code IS NULL ORDER BY guild_id, id"
        )
    ).fetchall()

    taken: dict[int, set[str]] = {}
    for schedule_id, guild_id, boss_name in rows:
        used = taken.setdefault(guild_id, set())
        code = generate_code(boss_name, used)
        used.add(code)
        connection.execute(
            sa.text("UPDATE party_schedule SET code = :code WHERE id = :id"),
            {"code": code, "id": schedule_id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("party_schedule", schema=None) as batch_op:
        batch_op.drop_constraint("uq_party_schedule_guild_code", type_="unique")
        batch_op.drop_column("code")

    # ### end Alembic commands ###
