"""drop clear record

Revision ID: 94d7522eba7b
Revises:03d0cd6a4f18
Create Date: 2026-09-09 13:03:45.274729
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "94d7522eba7b"
down_revision: str | None = "03d0cd6a4f18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clear_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clear_record_guild_period"))

    op.drop_table("clear_record")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clear_record",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("guild_id", sa.BIGINT(), nullable=False),
        sa.Column("schedule_id", sa.INTEGER(), nullable=True),
        sa.Column("character_id", sa.INTEGER(), nullable=False),
        sa.Column("boss_name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("difficulty", sa.VARCHAR(length=16), nullable=False),
        sa.Column("cleared_at", sa.DATETIME(), nullable=False),
        sa.Column("period_key", sa.VARCHAR(length=16), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schedule_id"], ["party_schedule.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "character_id",
            "boss_name",
            "difficulty",
            "period_key",
            name=op.f("uq_clear_record_period"),
        ),
    )
    with op.batch_alter_table("clear_record", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_clear_record_guild_period"), ["guild_id", "period_key"], unique=False
        )

    # ### end Alembic commands ###
