"""add boss image and one-off schedule

Revision ID: f8af749de87f
Revises:0cf95adcb590
Create Date: 2026-09-08 13:44:30.678225
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f8af749de87f'
down_revision: str | None = '0cf95adcb590'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_image',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('boss_name', sa.String(length=32), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'boss_name')
    )
    with op.batch_alter_table('party_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('once_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_schedule', schema=None) as batch_op:
        batch_op.drop_column('once_at')

    op.drop_table('boss_image')
    # ### end Alembic commands ###
